import { useState } from 'react';
import { useForm } from 'react-hook-form';
import toast from 'react-hot-toast';
import { LifeBuoy, MessageCircle, HelpCircle, ChevronDown, ChevronUp, Send } from 'lucide-react';

const FAQ = [
  {
    q: 'How do I know my admission status?',
    a: 'Go to Inquiry Status page to track your admission progress. You can see the current status, assigned counselor, and follow-up date.',
  },
  {
    q: 'How do I get my fee receipt?',
    a: 'Fee receipts are generated by our staff. Please contact your counselor or visit the campus for a printed receipt.',
  },
  {
    q: 'Can I change my enrolled course?',
    a: 'Course changes are subject to approval. Please raise a support ticket or contact your counselor directly.',
  },
  {
    q: 'How do I update my profile information?',
    a: 'Visit the Profile page from the sidebar. You can edit your personal information and save the changes.',
  },
  {
    q: 'I forgot my password. What should I do?',
    a: 'Use the Change Password option in your Profile page if you are logged in. Otherwise contact the admin office.',
  },
];

function FaqItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-gray-100 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-4 text-left bg-white hover:bg-gray-50 transition-colors"
      >
        <span className="text-sm font-medium text-gray-900">{q}</span>
        {open ? (
          <ChevronUp className="h-4 w-4 text-indigo-500 flex-shrink-0" />
        ) : (
          <ChevronDown className="h-4 w-4 text-gray-400 flex-shrink-0" />
        )}
      </button>
      {open && (
        <div className="px-5 pb-4 bg-white">
          <p className="text-sm text-gray-500 leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  );
}

const inputCls = 'w-full px-3 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 bg-white transition-colors';
const labelCls = 'block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5';

export default function Support() {
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const { register, handleSubmit, reset, formState: { errors } } = useForm();

  const onSubmit = async (data) => {
    setSending(true);
    // Simulate submit — in production, hook to an API
    await new Promise((res) => setTimeout(res, 1200));
    setSending(false);
    setSent(true);
    reset();
    toast.success('Support ticket submitted! We will get back to you shortly.');
    setTimeout(() => setSent(false), 4000);
  };

  return (
    <div className="p-4 lg:p-8 max-w-5xl mx-auto space-y-8">
      <div>
        <h2 className="text-xl font-bold text-gray-900">Help & Support</h2>
        <p className="text-sm text-gray-500 mt-0.5">Get help or contact your counselor</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Ticket Form */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-100 flex items-center gap-2">
            <MessageCircle className="h-4 w-4 text-indigo-600" />
            <h3 className="font-semibold text-gray-900">Submit a Ticket</h3>
          </div>
          <form onSubmit={handleSubmit(onSubmit)} className="p-6 space-y-4">
            <div>
              <label className={labelCls}>Category</label>
              <select {...register('category', { required: true })} className={inputCls}>
                <option value="">Select a category</option>
                <option value="admission">Admission Query</option>
                <option value="fees">Fees & Payment</option>
                <option value="course">Course Information</option>
                <option value="technical">Technical Issue</option>
                <option value="other">Other</option>
              </select>
              {errors.category && <p className="text-red-500 text-xs mt-1">Please select a category</p>}
            </div>
            <div>
              <label className={labelCls}>Subject</label>
              <input
                {...register('subject', { required: true })}
                className={inputCls}
                placeholder="Brief description of your issue"
              />
              {errors.subject && <p className="text-red-500 text-xs mt-1">Subject is required</p>}
            </div>
            <div>
              <label className={labelCls}>Message</label>
              <textarea
                {...register('message', { required: true })}
                rows={4}
                className={`${inputCls} resize-none`}
                placeholder="Describe your issue in detail..."
              />
              {errors.message && <p className="text-red-500 text-xs mt-1">Message is required</p>}
            </div>
            <button
              type="submit"
              disabled={sending || sent}
              className="w-full py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-semibold hover:bg-indigo-700 transition-colors disabled:opacity-60 flex items-center justify-center gap-2"
            >
              {sending ? (
                <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> Sending...</>
              ) : sent ? (
                '✓ Submitted!'
              ) : (
                <><Send className="h-4 w-4" /> Submit Ticket</>
              )}
            </button>
          </form>
        </div>

        {/* Contact + Info */}
        <div className="space-y-4">
          <div className="bg-gradient-to-br from-indigo-600 to-violet-700 rounded-2xl p-6 text-white">
            <LifeBuoy className="h-8 w-8 text-indigo-200 mb-3" />
            <h3 className="font-semibold text-lg mb-1">Contact Counselor</h3>
            <p className="text-indigo-200 text-sm">
              Your assigned counselor is the best point of contact for admission and course queries.
            </p>
            <div className="mt-4 pt-4 border-t border-white/20">
              <p className="text-xs text-indigo-200">Office Hours</p>
              <p className="text-sm font-medium">Mon–Sat · 9:00 AM – 6:00 PM</p>
            </div>
          </div>

          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
            <div className="flex items-center gap-2 mb-3">
              <HelpCircle className="h-4 w-4 text-indigo-600" />
              <h3 className="font-semibold text-gray-900 text-sm">Quick Info</h3>
            </div>
            <ul className="space-y-2 text-sm text-gray-600">
              <li className="flex items-start gap-2">
                <span className="text-indigo-500 mt-0.5">•</span>
                Response time: Within 24 business hours
              </li>
              <li className="flex items-start gap-2">
                <span className="text-indigo-500 mt-0.5">•</span>
                For urgent issues, call the campus helpline
              </li>
              <li className="flex items-start gap-2">
                <span className="text-indigo-500 mt-0.5">•</span>
                Track your inquiry on the Inquiry Status page
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* FAQ */}
      <div>
        <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <HelpCircle className="h-4 w-4 text-indigo-600" />
          Frequently Asked Questions
        </h3>
        <div className="space-y-2">
          {FAQ.map((item) => <FaqItem key={item.q} q={item.q} a={item.a} />)}
        </div>
      </div>
    </div>
  );
}
